# Generated by Django 4.1.2 on 2022-10-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
