# Generated by Django 4.1.2 on 2022-10-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='person_responsible',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
