# Generated by Django 4.1.2 on 2022-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todo_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Home', 'Home stuff'), ('Work', 'Work stuff')], max_length=20),
        ),
    ]
