# Generated by Django 4.1.2 on 2023-02-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='title',
        ),
    ]
