# Generated by Django 4.1.2 on 2023-03-01 20:53

from django.db import migrations, models
import todos_app.todos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_rename_text_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=30, validators=[todos_app.todos.validators.validate_dot]),
        ),
    ]
