# Generated by Django 4.1.7 on 2023-03-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
    ]
